[package]
name = "jaankaup_models"
version = "0.1.0"
authors = ["jaankaup <janne.a.kauppinen@student.jyu.fi>"]
edition = "2018"

[lib]

[dependencies]
jaankaup_core = { path = "../../jaankaup_core" }
