[package]
name = "jaankaup_algorithms"
version = "0.1.0"
authors = ["jaankaup <janne.a.kauppinen@student.jyu.fi>"]
edition = "2021"

[lib]

[dependencies]
bytemuck = { version = "1.4", features = ["derive"] }
jaankaup_core = { path = "../jaankaup_core" }
